import { prisma } from "../db/prisma.js";

// Clear existing users
await prisma.user.deleteMany();

// Create seed users
await prisma.user.createMany({
  data: [
    {
      firstName: "John",
      lastName: "Doe",
      age: 28,
      gender: "male",
      birthDate: "1995-05-15",
      height: 180,
      weight: 75,
      eyeColor: "Brown",
      hair: "Brown Straight",
      university: "MIT",
      company: "Tech Corp - Senior Developer - Engineering",
      address: "San Francisco, California, USA",
      crypto: "Bitcoin (BTC)",
      email: "john.doe@example.com",
      role: "ADMIN",
      team: "Engineering"
    },
    {
      firstName: "Jane",
      lastName: "Smith",
      age: 32,
      gender: "female",
      birthDate: "1991-08-22",
      height: 165,
      weight: 60,
      eyeColor: "Blue",
      hair: "Blonde Wavy",
      university: "Stanford",
      company: "Innovation Labs - Product Manager - Product",
      address: "New York, New York, USA",
      crypto: "Ethereum (ETH)",
      email: "jane.smith@example.com",
      role: "USER",
      team: "Product"
    },
    {
      firstName: "Michael",
      lastName: "Johnson",
      age: 45,
      gender: "male",
      birthDate: "1978-12-10",
      height: 175,
      weight: 82,
      eyeColor: "Green",
      hair: "Black Curly",
      university: "Harvard",
      company: "StartUp Inc - CTO - Executive",
      address: "Boston, Massachusetts, USA",
      crypto: "Solana (SOL)",
      email: "michael.johnson@example.com",
      role: "ADMIN",
      team: "Executive"
    },
    {
      firstName: "Emily",
      lastName: "Brown",
      age: 26,
      gender: "female",
      birthDate: "1997-03-18",
      height: 170,
      weight: 58,
      eyeColor: "Hazel",
      hair: "Red Straight",
      university: "UC Berkeley",
      company: "Design Studio - UX Designer - Design",
      address: "Los Angeles, California, USA",
      crypto: "Cardano (ADA)",
      email: "emily.brown@example.com",
      role: "USER",
      team: "Design"
    },
    {
      firstName: "David",
      lastName: "Wilson",
      age: 35,
      gender: "male",
      birthDate: "1988-07-25",
      height: 185,
      weight: 88,
      eyeColor: "Brown",
      hair: "Brown Straight",
      university: "Yale",
      company: "AI Research - Data Scientist - Research",
      address: "Seattle, Washington, USA",
      crypto: "Polygon (MATIC)",
      email: "david.wilson@example.com",
      role: "USER",
      team: "Research"
    },
    {
      firstName: "Sarah",
      lastName: "Martinez",
      age: 29,
      gender: "female",
      birthDate: "1994-11-30",
      height: 168,
      weight: 62,
      eyeColor: "Brown",
      hair: "Black Straight",
      university: "Columbia",
      company: "FinTech Solutions - Frontend Developer - Engineering",
      address: "Chicago, Illinois, USA",
      crypto: "Ripple (XRP)",
      email: "sarah.martinez@example.com",
      role: "USER",
      team: "Engineering"
    },
    {
      firstName: "James",
      lastName: "Anderson",
      age: 38,
      gender: "male",
      birthDate: "1985-06-14",
      height: 178,
      weight: 80,
      eyeColor: "Blue",
      hair: "Blonde Wavy",
      university: "Princeton",
      company: "Cloud Systems - DevOps Engineer - Operations",
      address: "Austin, Texas, USA",
      crypto: "Litecoin (LTC)",
      email: "james.anderson@example.com",
      role: "ADMIN",
      team: "Operations"
    },
    {
      firstName: "Lisa",
      lastName: "Thompson",
      age: 31,
      gender: "female",
      birthDate: "1992-09-05",
      height: 172,
      weight: 65,
      eyeColor: "Green",
      hair: "Auburn Curly",
      university: "Duke",
      company: "Marketing Pro - Marketing Manager - Marketing",
      address: "Miami, Florida, USA",
      crypto: "Dogecoin (DOGE)",
      email: "lisa.thompson@example.com",
      role: "USER",
      team: "Marketing"
    },
    {
      firstName: "Robert",
      lastName: "Garcia",
      age: 42,
      gender: "male",
      birthDate: "1981-04-20",
      height: 182,
      weight: 85,
      eyeColor: "Brown",
      hair: "Black Short",
      university: "UCLA",
      company: "Security First - Security Engineer - Security",
      address: "Phoenix, Arizona, USA",
      crypto: "Chainlink (LINK)",
      email: "robert.garcia@example.com",
      role: "ADMIN",
      team: "Security"
    },
    {
      firstName: "Amanda",
      lastName: "Lee",
      age: 27,
      gender: "female",
      birthDate: "1996-01-12",
      height: 163,
      weight: 55,
      eyeColor: "Brown",
      hair: "Black Long",
      university: "Cornell",
      company: "Creative Agency - Graphic Designer - Design",
      address: "Portland, Oregon, USA",
      crypto: "Polkadot (DOT)",
      email: "amanda.lee@example.com",
      role: "USER",
      team: "Design"
    },
    {
      firstName: "Christopher",
      lastName: "White",
      age: 33,
      gender: "male",
      birthDate: "1990-07-08",
      height: 177,
      weight: 78,
      eyeColor: "Blue",
      hair: "Brown Short",
      university: "Northwestern",
      company: "Data Corp - Backend Developer - Engineering",
      address: "Denver, Colorado, USA",
      crypto: "Avalanche (AVAX)",
      email: "christopher.white@example.com",
      role: "USER",
      team: "Engineering"
    },
    {
      firstName: "Jessica",
      lastName: "Harris",
      age: 30,
      gender: "female",
      birthDate: "1993-10-16",
      height: 169,
      weight: 61,
      eyeColor: "Hazel",
      hair: "Blonde Straight",
      university: "Brown",
      company: "HR Solutions - HR Manager - Human Resources",
      address: "Philadelphia, Pennsylvania, USA",
      crypto: "Cosmos (ATOM)",
      email: "jessica.harris@example.com",
      role: "USER",
      team: "Human Resources"
    },
    {
      firstName: "Daniel",
      lastName: "Clark",
      age: 36,
      gender: "male",
      birthDate: "1987-02-28",
      height: 183,
      weight: 83,
      eyeColor: "Green",
      hair: "Red Wavy",
      university: "Dartmouth",
      company: "Tech Innovations - Full Stack Developer - Engineering",
      address: "San Diego, California, USA",
      crypto: "Uniswap (UNI)",
      email: "daniel.clark@example.com",
      role: "USER",
      team: "Engineering"
    },
    {
      firstName: "Michelle",
      lastName: "Rodriguez",
      age: 34,
      gender: "female",
      birthDate: "1989-05-22",
      height: 166,
      weight: 59,
      eyeColor: "Brown",
      hair: "Brown Curly",
      university: "Penn",
      company: "Finance Group - Financial Analyst - Finance",
      address: "Dallas, Texas, USA",
      crypto: "Aave (AAVE)",
      email: "michelle.rodriguez@example.com",
      role: "ADMIN",
      team: "Finance"
    },
    {
      firstName: "Matthew",
      lastName: "Lewis",
      age: 40,
      gender: "male",
      birthDate: "1983-12-03",
      height: 179,
      weight: 81,
      eyeColor: "Blue",
      hair: "Gray Short",
      university: "Vanderbilt",
      company: "Consulting Ltd - Business Consultant - Consulting",
      address: "Nashville, Tennessee, USA",
      crypto: "Stellar (XLM)",
      email: "matthew.lewis@example.com",
      role: "USER",
      team: "Consulting"
    },
    {
      firstName: "Ashley",
      lastName: "Walker",
      age: 25,
      gender: "female",
      birthDate: "1998-08-19",
      height: 164,
      weight: 57,
      eyeColor: "Green",
      hair: "Blonde Curly",
      university: "Rice",
      company: "Social Media Co - Content Creator - Marketing",
      address: "Houston, Texas, USA",
      crypto: "Tezos (XTZ)",
      email: "ashley.walker@example.com",
      role: "USER",
      team: "Marketing"
    },
    {
      firstName: "Kevin",
      lastName: "Hall",
      age: 39,
      gender: "male",
      birthDate: "1984-03-11",
      height: 181,
      weight: 84,
      eyeColor: "Brown",
      hair: "Black Short",
      university: "Georgetown",
      company: "Legal Firm - Legal Counsel - Legal",
      address: "Washington, DC, USA",
      crypto: "Monero (XMR)",
      email: "kevin.hall@example.com",
      role: "ADMIN",
      team: "Legal"
    },
    {
      firstName: "Stephanie",
      lastName: "Allen",
      age: 28,
      gender: "female",
      birthDate: "1995-11-25",
      height: 167,
      weight: 60,
      eyeColor: "Blue",
      hair: "Brown Long",
      university: "Emory",
      company: "Healthcare Tech - Product Designer - Design",
      address: "Atlanta, Georgia, USA",
      crypto: "Dash (DASH)",
      email: "stephanie.allen@example.com",
      role: "USER",
      team: "Design"
    },
    {
      firstName: "Brian",
      lastName: "Young",
      age: 37,
      gender: "male",
      birthDate: "1986-06-07",
      height: 176,
      weight: 79,
      eyeColor: "Hazel",
      hair: "Brown Wavy",
      university: "USC",
      company: "Mobile Apps - iOS Developer - Engineering",
      address: "San Jose, California, USA",
      crypto: "Zcash (ZEC)",
      email: "brian.young@example.com",
      role: "USER",
      team: "Engineering"
    },
    {
      firstName: "Nicole",
      lastName: "King",
      age: 32,
      gender: "female",
      birthDate: "1991-09-14",
      height: 171,
      weight: 63,
      eyeColor: "Brown",
      hair: "Black Straight",
      university: "Notre Dame",
      company: "E-commerce Plus - Sales Manager - Sales",
      address: "Minneapolis, Minnesota, USA",
      crypto: "VeChain (VET)",
      email: "nicole.king@example.com",
      role: "USER",
      team: "Sales"
    },
    {
      firstName: "Justin",
      lastName: "Wright",
      age: 41,
      gender: "male",
      birthDate: "1982-04-02",
      height: 184,
      weight: 86,
      eyeColor: "Green",
      hair: "Blonde Short",
      university: "Boston College",
      company: "Investment Bank - Investment Banker - Finance",
      address: "Charlotte, North Carolina, USA",
      crypto: "Algorand (ALGO)",
      email: "justin.wright@example.com",
      role: "ADMIN",
      team: "Finance"
    },
    {
      firstName: "Megan",
      lastName: "Lopez",
      age: 29,
      gender: "female",
      birthDate: "1994-07-29",
      height: 165,
      weight: 58,
      eyeColor: "Brown",
      hair: "Brown Curly",
      university: "Tufts",
      company: "EdTech Startup - Education Specialist - Education",
      address: "Detroit, Michigan, USA",
      crypto: "Hedera (HBAR)",
      email: "megan.lopez@example.com",
      role: "USER",
      team: "Education"
    },
    {
      firstName: "Ryan",
      lastName: "Hill",
      age: 35,
      gender: "male",
      birthDate: "1988-01-18",
      height: 180,
      weight: 82,
      eyeColor: "Blue",
      hair: "Brown Short",
      university: "Wake Forest",
      company: "Gaming Studio - Game Developer - Engineering",
      address: "Raleigh, North Carolina, USA",
      crypto: "The Graph (GRT)",
      email: "ryan.hill@example.com",
      role: "USER",
      team: "Engineering"
    },
    {
      firstName: "Lauren",
      lastName: "Scott",
      age: 26,
      gender: "female",
      birthDate: "1997-10-05",
      height: 168,
      weight: 61,
      eyeColor: "Hazel",
      hair: "Red Long",
      university: "Syracuse",
      company: "Media Group - Journalist - Media",
      address: "Baltimore, Maryland, USA",
      crypto: "Maker (MKR)",
      email: "lauren.scott@example.com",
      role: "USER",
      team: "Media"
    },
    {
      firstName: "Eric",
      lastName: "Green",
      age: 43,
      gender: "male",
      birthDate: "1980-08-31",
      height: 178,
      weight: 80,
      eyeColor: "Brown",
      hair: "Black Short",
      university: "Lehigh",
      company: "Manufacturing Co - Operations Manager - Operations",
      address: "Pittsburgh, Pennsylvania, USA",
      crypto: "Compound (COMP)",
      email: "eric.green@example.com",
      role: "ADMIN",
      team: "Operations"
    },
    {
      firstName: "Rachel",
      lastName: "Adams",
      age: 30,
      gender: "female",
      birthDate: "1993-12-12",
      height: 170,
      weight: 64,
      eyeColor: "Blue",
      hair: "Blonde Wavy",
      university: "Tulane",
      company: "Travel Agency - Travel Coordinator - Operations",
      address: "New Orleans, Louisiana, USA",
      crypto: "Synthetix (SNX)",
      email: "rachel.adams@example.com",
      role: "USER",
      team: "Operations"
    },
    {
      firstName: "Tyler",
      lastName: "Baker",
      age: 34,
      gender: "male",
      birthDate: "1989-05-06",
      height: 182,
      weight: 85,
      eyeColor: "Green",
      hair: "Brown Curly",
      university: "William & Mary",
      company: "Architecture Firm - Architect - Design",
      address: "Richmond, Virginia, USA",
      crypto: "Yearn Finance (YFI)",
      email: "tyler.baker@example.com",
      role: "USER",
      team: "Design"
    },
    {
      firstName: "Samantha",
      lastName: "Nelson",
      age: 27,
      gender: "female",
      birthDate: "1996-03-23",
      height: 166,
      weight: 59,
      eyeColor: "Brown",
      hair: "Black Long",
      university: "Pepperdine",
      company: "Fashion Brand - Fashion Designer - Design",
      address: "Los Angeles, California, USA",
      crypto: "Curve (CRV)",
      email: "samantha.nelson@example.com",
      role: "USER",
      team: "Design"
    },
    {
      firstName: "Brandon",
      lastName: "Carter",
      age: 38,
      gender: "male",
      birthDate: "1985-11-09",
      height: 179,
      weight: 81,
      eyeColor: "Blue",
      hair: "Blonde Short",
      university: "SMU",
      company: "Real Estate Group - Real Estate Agent - Sales",
      address: "Dallas, Texas, USA",
      crypto: "Sushi (SUSHI)",
      email: "brandon.carter@example.com",
      role: "USER",
      team: "Sales"
    },
    {
      firstName: "Kimberly",
      lastName: "Mitchell",
      age: 31,
      gender: "female",
      birthDate: "1992-06-17",
      height: 169,
      weight: 62,
      eyeColor: "Hazel",
      hair: "Brown Straight",
      university: "Baylor",
      company: "Insurance Corp - Insurance Analyst - Finance",
      address: "Indianapolis, Indiana, USA",
      crypto: "1inch (1INCH)",
      email: "kimberly.mitchell@example.com",
      role: "USER",
      team: "Finance"
    },
    {
      firstName: "Gregory",
      lastName: "Perez",
      age: 44,
      gender: "male",
      birthDate: "1979-02-14",
      height: 181,
      weight: 87,
      eyeColor: "Brown",
      hair: "Gray Short",
      university: "Texas A&M",
      company: "Energy Solutions - Chief Engineer - Engineering",
      address: "Houston, Texas, USA",
      crypto: "Filecoin (FIL)",
      email: "gregory.perez@example.com",
      role: "ADMIN",
      team: "Engineering"
    },
    {
      firstName: "Melissa",
      lastName: "Roberts",
      age: 28,
      gender: "female",
      birthDate: "1995-09-21",
      height: 167,
      weight: 60,
      eyeColor: "Green",
      hair: "Red Wavy",
      university: "University of Miami",
      company: "Biotech Lab - Research Scientist - Research",
      address: "Miami, Florida, USA",
      crypto: "Enjin (ENJ)",
      email: "melissa.roberts@example.com",
      role: "USER",
      team: "Research"
    }
  ]
});

console.log("Seeding completed! Added 32 users.");
